### ISSUE TITLE
Python 3.6 Support

### ISSUE THREAD

**Issue by nfitzen** [AmanoTeam/python-anilist#10]
While working on this project, I've encountered times where I'd like to use a nice Python feature but was unable to do so due to the Python 3.6 requirement. (Examples include [`dataclasses`][1] and [`importlib.resources`][2].)

I'm making this issue to suggest moving the minimum Python version up to 3.7. I don't know how much of an effect this'll have on existing projects, however, so that'll need to be weighed in. Would this be possible?

[1]: https://docs.python.org/3.7/library/dataclasses.html
[2]: https://docs.python.org/3.7/library/importlib.html#module-importlib.resources

**Comment by AndrielFR** [comment]
It's okay to do that, I think. The other option would be to remove the dependency on these functions.

**Comment by nfitzen** [comment]
@AndrielFR True. It's certainly not necessary right now, but I was just wondering whether it's a loose requirement.

**Comment by AndrielFR** [comment]
> @AndrielFR True. It's certainly not necessary right now, but I was just wondering whether it's a loose requirement.

I will drop Python 3.6 support.
